# fly.toml app configuration file generated for odin-mini-message-board-nameless-voice-3412 on 2024-09-12T12:12:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'odin-mini-message-board-nameless-voice-3412'
primary_region = 'lhr'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
